export enum IconEnum {
    ArrowTopRight = 'arrow-top-right',
    ArrowLink = 'arrow-link',
    Atom = 'atom',
    Book = 'book',
    CircleArrowUp = 'circle-arrow-up',
    CoinStack = 'coin-stack',
    Dart = 'dart',
    Event = 'event',
    Menu = 'menu',
    Meter = 'meter',
    OpenSource = 'open-source',
    PieChart = 'pie-chart',
    Search = 'search',
    Ticket = 'ticket',
    UserCard = 'user-card',
    UserWarning = 'user-warning',
    XClone = 'x-clone',
}
