import type { ComponentType, SvelteComponent } from 'svelte'
import { IconEnum } from './icon.enums'
import {
    ArrowTopRight,
    Atom,
    Book,
    Carousel,
    CircleArrowUp,
    CircleHive,
    CoinStack,
    Convergence,
    DAO,
    Dart,
    Event,
    Firefly,
    Gaming,
    HorizontalCircleChains,
    IOTA,
    LayeredRings,
    Menu,
    MetaMask,
    Meter,
    OpenSource,
    Overlap,
    PieChart,
    RestAPI,
    Search,
    SecurityShield,
    Shimmer,
    SignalBars,
    SmallArrowBottomRight,
    SmartContract,
    SquareDots,
    SquareLayers,
    Ticket,
    TripleRing,
    UserCard,
    UserWarning,
    VerticalBlockChains,
    XClone,
} from './icons'

export const ICON_MAP: Record<IconEnum, ComponentType<SvelteComponent>> = {
    [IconEnum.ArrowTopRight]: ArrowTopRight,
    [IconEnum.Atom]: Atom,
    [IconEnum.Book]: Book,
    [IconEnum.Carousel]: Carousel,
    [IconEnum.CircleArrowUp]: CircleArrowUp,
    [IconEnum.CircleHive]: CircleHive,
    [IconEnum.CoinStack]: CoinStack,
    [IconEnum.Convergence]: Convergence,
    [IconEnum.DAO]: DAO,
    [IconEnum.Dart]: Dart,
    [IconEnum.Event]: Event,
    [IconEnum.Firefly]: Firefly,
    [IconEnum.Gaming]: Gaming,
    [IconEnum.HorizontalCircleChains]: HorizontalCircleChains,
    [IconEnum.IOTA]: IOTA,
    [IconEnum.LayeredRings]: LayeredRings,
    [IconEnum.Menu]: Menu,
    [IconEnum.MetaMask]: MetaMask,
    [IconEnum.Meter]: Meter,
    [IconEnum.OpenSource]: OpenSource,
    [IconEnum.Overlap]: Overlap,
    [IconEnum.PieChart]: PieChart,
    [IconEnum.RestAPI]: RestAPI,
    [IconEnum.Search]: Search,
    [IconEnum.SecurityShield]: SecurityShield,
    [IconEnum.Shimmer]: Shimmer,
    [IconEnum.SignalBars]: SignalBars,
    [IconEnum.SmallArrowBottomRight]: SmallArrowBottomRight,
    [IconEnum.SmartContract]: SmartContract,
    [IconEnum.SquareDots]: SquareDots,
    [IconEnum.SquareLayers]: SquareLayers,
    [IconEnum.Ticket]: Ticket,
    [IconEnum.TripleRing]: TripleRing,
    [IconEnum.UserCard]: UserCard,
    [IconEnum.UserWarning]: UserWarning,
    [IconEnum.VerticalBlockChains]: VerticalBlockChains,
    [IconEnum.XClone]: XClone,
}
