export enum IconEnum {
    Bullet = 'bullet',
    CollectiveInvitation = 'collective-invitation',
    ConflictOfInterest = 'conflict-of-interest',
    Duplication = 'duplication',
    Funding = 'funding',
    Interview = 'interview',
    MarketValue = 'market-value',
    Menu = 'menu',
    OpenSource = 'open-source',
    RelevanceImpact = 'relevance-impact',
    Risk = 'risk',
    Submission = 'submission',
    UpRightArrow = 'up-right-arrow',
}
