import type { ComponentType, SvelteComponent } from 'svelte'
import { IconEnum } from './icon.enums'
import {
    ArrowTopRight,
    ArrowLink,
    Atom,
    Book,
    CircleArrowUp,
    CoinStack,
    Dart,
    Event,
    Menu,
    Meter,
    OpenSource,
    PieChart,
    Search,
    Ticket,
    UserCard,
    UserWarning,
    XClone,
} from './icons'

export const ICON_MAP: Record<IconEnum, ComponentType<SvelteComponent>> = {
    [IconEnum.ArrowTopRight]: ArrowTopRight,
    [IconEnum.ArrowLink]: ArrowLink,
    [IconEnum.Atom]: Atom,
    [IconEnum.Book]: Book,
    [IconEnum.CircleArrowUp]: CircleArrowUp,
    [IconEnum.CoinStack]: CoinStack,
    [IconEnum.Dart]: Dart,
    [IconEnum.Event]: Event,
    [IconEnum.Menu]: Menu,
    [IconEnum.Meter]: Meter,
    [IconEnum.OpenSource]: OpenSource,
    [IconEnum.PieChart]: PieChart,
    [IconEnum.Search]: Search,
    [IconEnum.Ticket]: Ticket,
    [IconEnum.UserCard]: UserCard,
    [IconEnum.UserWarning]: UserWarning,
    [IconEnum.XClone]: XClone,
}
